"""track history table

Revision ID: 326f83f4d2da
Revises: 
Create Date: 2021-03-14 07:18:19.022787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326f83f4d2da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_history',
    sa.Column('song_name', sa.String(length=200), nullable=True),
    sa.Column('artist_name', sa.String(length=200), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('played_at')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_history')
    # ### end Alembic commands ###
